name: boing_boot
description: A framework for building web applications in Dart based on the Spring Boot framework.
version: 0.0.1
homepage: https://github.com/evandersondev/boing_boot

environment:
  sdk: ">=3.7.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
